export default {
    login: 'LoginScreen',
    signup: 'SignupScreen',
    signup2: 'SignupScreen2',
    authTopTabs: 'AuthTopTabs',
    otpScreen: 'OTPScreen',
    forgotScreen: 'ForgotPasswordScreen',
    forgotOtpScreen: 'ForgotOtpScreen',
    resetPasswordScreen: 'ResetPasswordScreen',
    drawerRoutes: 'DrawerRoutes',
    home: 'Home',
    jobs: 'Jobs',
    chat: 'Chat',
    profile: 'Profile',
    tabRoutes: 'TabRoutes',
    profileStack: 'ProfileStack',
    profileScreen: 'ProfileScreen',
    editDetailsScreen: 'EditDetailsScreen',
    viewRatingsScreen: 'ViewRatingsScreen',
};
