export default {
    welcomeBack: 'Welcome Back',
    welcomeText: 'Welcome to Helpr! We are here to help with your service requests.',
    signIn: 'Sign In',
    verticalPipe: '|',
    signUp: 'Sign Up',
    email: 'Email',
    password: 'Password',
    rememberMe: 'Remember Me',
    forgetPassword: 'Forgot password?',
    doNotHaveAccount: `Don't have an account?`,
    emailRequired: 'Email is required.',
    passwordRequired: 'Password is required',
    minPassword: 'Minimum 8 character required',
    maxPassword: 'Maximum limit reached',
    invalidEmail: 'Email is invalid',
    invalidPassword: 'Password is invalid',
    createAccount: 'Create Account',
    firstname: 'First Name',
    lastname: 'Last Name',
    mobileNumber: 'Mobile Number',
    confirmPassword: 'Confirm Password',
    next: 'Next',
    haveAccount: 'Already have an account?',
    uploadPic: 'Upload Profile Picture',
    firstnameRequired: 'First Name is required',
    lastnameRequired: 'Last Name is required',
    mobileRequired: 'Mobile Number is required',
    confirmPasswordRequired: 'Confirm Password is required',
    noMatchPassword: 'Password does not match',
    minName: 'Minimun 3 character required',
    maxName: 'Maximum limit reached',
    invalidNumber: 'Mobile Number is invalid',
};
