export default {
    welcomeBack: 'Welcome Back',
    welcomeText: 'Welcome to Helpr! We are here to help with your service requests.',
    signIn: 'Sign In',
    verticalPipe: '|',
    signUp: 'Sign Up',
    email: 'Email',
    password: 'Password',
    rememberMe: 'Remember Me',
    forgetPassword: 'Forgot password?',
    doNotHaveAccount: `Don't have an account?`,
    emailRequired: 'Email is required',
    passwordRequired: 'Password is required',
    minPassword: 'Minimum 8 character required',
    maxPassword: 'Maximum limit reached',
    invalidEmail: 'Email is invalid',
    invalidPassword: 'Password is invalid',
    createAccount: 'Create Account',
    firstname: 'First Name',
    lastname: 'Last Name',
    mobileNumber: 'Mobile Number',
    confirmPassword: 'Confirm Password',
    next: 'Next',
    haveAccount: 'Already have an account?',
    uploadPic: 'Upload Profile Picture',
    photoRequired: 'Photo is required',
    firstnameRequired: 'First Name is required',
    lastnameRequired: 'Last Name is required',
    mobileRequired: 'Mobile Number is required',
    confirmPasswordRequired: 'Confirm Password is required',
    noMatchPassword: 'Password does not match',
    minName: 'Minimun 3 character required',
    maxName: 'Maximum limit reached',
    invalidNumber: 'Mobile Number is invalid',
    signup2: 'Sign Up - Step 2',
    verifyOTP: 'Verify Email OTP',
    otpHead: 'OTP has been sent on Email',
    otp: 'OTP',
    resend: 'Resend?',
    forgotPassword: 'Forgot Password',
    forgot: 'Forgot',
    verify: 'Verify',
    backToLogin: 'Back to Login Page',
    resetPassword: 'Reset Password',
    submit: 'Submit',
    subscription: 'Subscription',
    premium: 'Premium',
    standard: 'Standard',
    basic: 'Basic',
    price1: '$199',
    price2: '$120',
    price3: '$80',
    m: '/m',
    planIncludes: 'This plan Includes:',
    text1: 'Premium Customer Support',
    text2: 'Unlimited Requests',
    text3: 'Add Unlimited Expertise',
    text4: 'Unlimited Requests',
    text5: '24*7 Response for Contact',
    text6: 'Unlimited Requests',
    text7: 'Premium Customer Support',
    text8: 'Unlimited Requests',
    applyCode: 'Apply Promo Code',
    apply: 'Apply',
    payNow: 'Pay Now',
    profile: 'Profile',
    ratings: 'View Ratings',
    availability: 'Availability',
    emailAddress: 'Email Address',
    exampleMail: 'johnmethon@gmail.com',
    phNumber: 'Phone Number',
    phn: '+91 9857452030',
    expertise: 'Expertise',
    expertiseName: 'Expertise Name',
    exampleText: '$10/h',
    review: 'Review',
    cancelation: 'Cancelation Policy',
    changePassword: 'Change Password',
    editProfile: 'Edit Profile',
    updateProfile: 'Update Profile',
    addServices: '+ Add More Services',
    selectServices: 'Select your expertise or the services',
    electronicSignature: 'Enter your name for Electronic Signature',
    iAgree: 'I agree with ',
    contractText: 'contract waiver',
    confirmContract: 'Confirm contract has been read and accepted',
    viewRatings: 'View Ratings',
    review: '- 150 Review',
    allRatings: 'All Ratings',
    allReview: 'All Reviews',
};
