import {StyleSheet} from 'react-native';
import {
  Colors,
  horizontalScale,
  moderateScale,
  verticalScale,
} from '../../../theme';

export const styles = StyleSheet.create({
  main: {
    flex: 1,
    backgroundColor: Colors.white,
  },
  topImage: {
    height: verticalScale(180),
    width: horizontalScale(375),
    borderTopLeftRadius: moderateScale(12),
    borderTopRightRadius: moderateScale(12),
    marginTop: verticalScale(16),
  },
  welcomeView: {
    alignItems: 'center',
    padding: moderateScale(15),
  },
  welcomeText: {
    fontSize: moderateScale(24),
    fontWeight: '600',
    color: Colors.theme,
  },
  subWelcomeText: {
    fontSize: moderateScale(16),
    color: Colors.black,
    textAlign: 'center',
    marginTop: verticalScale(25),
  },
  tabTextView: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginBottom: verticalScale(10),
  },
  tabText: {
    fontSize: moderateScale(18),
    color: Colors.theme,
    fontWeight: '500',
    marginTop: verticalScale(13),
  },
  focusedText: {
    fontSize: moderateScale(18),
    color: Colors.theme,
    fontWeight: '500',
    marginTop: verticalScale(13),
  },
  unFocusedText: {
    fontSize: moderateScale(18),
    color: Colors.black,
    fontWeight: '500',
    marginTop: verticalScale(13),
  },
  pipeLine: {
    color: Colors.black,
    fontSize: moderateScale(18),
    paddingHorizontal: horizontalScale(10),
    marginTop: verticalScale(13),
  },
  uploadOuterView: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: verticalScale(10),
  },
  uploadInnerView: {
    marginBottom: verticalScale(10),
    height: moderateScale(120),
    width: moderateScale(120),
    borderWidth: moderateScale(1),
    borderColor: Colors.theme,
    borderRadius: moderateScale(100),
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: Colors.offWhite,
  },
  uploadText: {
    textAlign: 'center',
    marginTop: verticalScale(10),
    color: Colors.gray,
    fontWeight: '500',
    fontSize: moderateScale(13),
  },
  pictureText: {
    textAlign: 'center',
    color: Colors.gray,
    fontWeight: '500',
    fontSize: moderateScale(13),
  },
  outerTextInputView: {
    marginBottom: verticalScale(12),
  },
  textInputView: {
    paddingHorizontal: horizontalScale(10),
    marginHorizontal: horizontalScale(10),
    borderWidth: moderateScale(1),
    borderColor: Colors.theme,
    height: verticalScale(50),
    borderRadius: moderateScale(8),
    backgroundColor: Colors.offWhite,
    borderWidth: moderateScale(1),
  },
  textInput: {
    fontSize: moderateScale(12),
    color: Colors.black,
    fontWeight: '500',
    flex: 1,
  },
  errorView: {
    paddingHorizontal: horizontalScale(20),
    top: verticalScale(-5)
  },
  errorText: {
    color: Colors.red,
        fontSize: moderateScale(10),
        fontWeight: '500',
  },
  photoError: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  photoErrorText: {
    color: Colors.red,
    fontSize: moderateScale(10),
    top: verticalScale(-7),
  },
  button: {
    backgroundColor: Colors.theme,
    justifyContent: 'center',
    alignItems: 'center',
    marginHorizontal: horizontalScale(120),
    marginTop: verticalScale(8),
    padding: moderateScale(15),
    marginBottom: verticalScale(15),
    borderRadius: moderateScale(10),
  },
  buttonText: {
    color: Colors.white,
    fontWeight: '600',
    fontSize: moderateScale(16),
  },
  createAccount: {
    textAlign: 'center',
    color: Colors.theme,
    textDecorationLine: 'underline',
    fontWeight: '600',
    marginBottom: verticalScale(20),
    fontSize: moderateScale(12),
  },
  inputOuterView: {
    marginTop: verticalScale(5),
  },
  inputInnerView: {
    marginBottom: verticalScale(10),
    height: verticalScale(100),
    borderWidth: moderateScale(1),
    borderColor: Colors.theme,
    borderRadius: moderateScale(5),
    marginHorizontal: horizontalScale(10),
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: Colors.offWhite,
  },
  inputUploadText: {
    textAlign: 'center',
    marginTop: verticalScale(8),
    color: Colors.gray,
    fontSize: moderateScale(12),
    fontWeight: '500',
  },
  dropdown: {
    height: 50,
    borderColor: Colors.theme,
    borderWidth: moderateScale(1),
    borderRadius: 8,
    // paddingHorizontal: 8,
    marginHorizontal: horizontalScale(10),
  },
  dropdownContainer: {
    flex: 1,
    justifyContent: "center",
    // alignItems: "center",
    borderWidth: moderateScale(1),
    borderColor: Colors.theme,
    marginHorizontal: horizontalScale(10),
    borderRadius: moderateScale(5),
    // borderTopLeftRadius: verticalScale(5),
    // borderTopRightRadius: verticalScale(5),
    backgroundColor: Colors.offWhite,
    height: verticalScale(50),
    // textAlignVertical: "center",
  },
  dropdownInnerView: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginHorizontal: horizontalScale(10),
    // textAlignVertical: "center",
  },
  dropdownText: {
    color: Colors.gray,
    // paddingVertical: verticalScale(10),
    fontWeight: '500',
    fontSize: moderateScale(12),
    // textAlignVertical: "center",
    // justifyContent: "center",
    // alignItems: "center"
  },
  dropdownTextSelected: {
    color: Colors.black,
    paddingVertical: verticalScale(10),
    fontWeight: '500',
    fontSize: moderateScale(12),
  },
  option: {
    paddingTop: verticalScale(3),
    paddingHorizontal: horizontalScale(10),
    // borderBottomWidth: moderateScale(1),
    // borderColor: Colors.gray
    // top: verticalScale(500),
  },
  optionText: {
    color: Colors.black,
    fontSize: moderateScale(12),
    fontWeight: '500',
},
  modalOuterView2: {
    alignItems: 'center',
    top: verticalScale(633),
    // flex: 1
  },
  modalView: {
    width: horizontalScale(355),
    borderWidth: moderateScale(1),
    borderColor: Colors.theme,
    borderBottomLeftRadius: verticalScale(5),
    borderBottomRightRadius: verticalScale(5),
    backgroundColor: Colors.offWhite,
  },
  checkboxContainer: {
    flexDirection: 'row',
    alignItems: "center",
  },
  checkbox: {
    marginLeft: horizontalScale(13),
    borderColor: Colors.theme,
    borderRadius: moderateScale(5),
    transform: [{scaleX: moderateScale(0.8)}, {scaleY: moderateScale(0.8)}],
  },
  contractView: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  label: {
    marginVertical: verticalScale(6),
    color: Colors.gray,
    fontSize: moderateScale(11),
    fontWeight: '500',
    marginLeft: horizontalScale(1),
  },
  contractText: {
    color: Colors.theme,
    textDecorationLine: 'underline',
    fontSize: moderateScale(11),
    fontWeight: '500',
  },
  confirmContract: {
    color: Colors.gray,
    marginLeft: horizontalScale(47),
    top: verticalScale(-5),
    fontSize: moderateScale(11),
    fontWeight: '500',
  },
  modalOuterView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
  },
  modalInnerView: {
    width: horizontalScale(300),
    backgroundColor: Colors.white,
    borderRadius: moderateScale(10),
    padding: moderateScale(10),
    shadowColor: '#000',
    shadowOffset: {
      width: horizontalScale(2),
      height: verticalScale(2),
    },
    shadowOpacity: 0.25,
    shadowRadius: moderateScale(4),
    elevation: moderateScale(2),
  },
  selectOneText: {
    padding: moderateScale(10),
    color: Colors.black,
    fontSize: moderateScale(15),
    fontWeight: '700',
  },
  labelText: {
    color: Colors.black,
    fontSize: moderateScale(12),
    fontWeight: '500',
  },
  labelView: {
    padding: moderateScale(10),
    backgroundColor: Colors.offWhite,
    marginTop: verticalScale(10),
  },
  cancelView: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
  },
});
